#!/bin/sh
apt-get install -y software-properties-common
if [[ $(grep -cF trusty /etc/lsb-release) > 0 ]]; then
  add-apt-repository -y ppa:kevinkreiser/czmq
  apt-get update -o Dir::Etc::sourcelist="sources.list.d/kevinkreiser-czqm-$(lsb_release -c -s).list" -o APT::Get::List-Cleanup="0"
fi
